// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhy8QjAlojn4NiJgjoZgAMfxAXpIPTMLk',
    appId: '1:1025952478914:web:7fc1abb2bc1bd373b86d5b',
    messagingSenderId: '1025952478914',
    projectId: 'livegame-c142a',
    authDomain: 'livegame-c142a.firebaseapp.com',
    databaseURL: 'https://livegame-c142a-default-rtdb.firebaseio.com',
    storageBucket: 'livegame-c142a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8G2YWM5wvgIBstFMeIxkeTFzOeYmWxY',
    appId: '1:1025952478914:android:ed16c2eb2216eeacb86d5b',
    messagingSenderId: '1025952478914',
    projectId: 'livegame-c142a',
    databaseURL: 'https://livegame-c142a-default-rtdb.firebaseio.com',
    storageBucket: 'livegame-c142a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9M3Fg69ySqJGVJEHRvcwUiI19s36_xlk',
    appId: '1:1025952478914:ios:1c4990497f4b4d0eb86d5b',
    messagingSenderId: '1025952478914',
    projectId: 'livegame-c142a',
    databaseURL: 'https://livegame-c142a-default-rtdb.firebaseio.com',
    storageBucket: 'livegame-c142a.appspot.com',
    iosBundleId: 'com.example.livegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9M3Fg69ySqJGVJEHRvcwUiI19s36_xlk',
    appId: '1:1025952478914:ios:1c4990497f4b4d0eb86d5b',
    messagingSenderId: '1025952478914',
    projectId: 'livegame-c142a',
    databaseURL: 'https://livegame-c142a-default-rtdb.firebaseio.com',
    storageBucket: 'livegame-c142a.appspot.com',
    iosBundleId: 'com.example.livegame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhy8QjAlojn4NiJgjoZgAMfxAXpIPTMLk',
    appId: '1:1025952478914:web:15efa9018caae042b86d5b',
    messagingSenderId: '1025952478914',
    projectId: 'livegame-c142a',
    authDomain: 'livegame-c142a.firebaseapp.com',
    databaseURL: 'https://livegame-c142a-default-rtdb.firebaseio.com',
    storageBucket: 'livegame-c142a.appspot.com',
  );

}